### ISSUE TITLE
loading sets from "script-output"

### ISSUE THREAD

**Issue by Flow86** [rk84/autofill#5]
Hi,
is it possible to automatically load (set-)scripts in "script-output" directory?

**Comment by rk84** [comment]
I'm confused. What do you wish to do exactly?

**Comment by Flow86** [comment]
okay, I'll try to explain:

currently, the mod has a fixed list of sets loaded by default (loader.addSets "settings/...")

I thought about kind of "set-directory" where users can place there set files, which are loaded then automatically (from outside the mod's zip file)

so you dont have to enter those complicated commands to create sets inside the game and ones can share there sets

**Comment by rk84** [comment]
I don't think there is clear method to read those files. Workaround might exist, but I would like a official method that does not desynch.

Heres modding interface request relate to this.
[Client-side scripts to send custom events to sim; readfile()](https://forums.factorio.com/viewtopic.php?f=28&t=16824&hilit=read+file)
