### ISSUE TITLE
Seems to be non-functional in 0.12.30?

### ISSUE THREAD

**Issue by yukihyou** [rk84/autofill#7]
Started a new game in 0.12.30 with a number of mods, then noticed Autofill wasn't working. Tried loading the save with only Autofill enabled, as well as starting a new game and cheating in a turret to test - both failed silently. Tested on 0.12.29 and it seems to work perfectly first time.

Let me know if there is additional testing/debugging I could do to assist.

**Comment by Flow86** [comment]
Hi,
Im using autofill and 0.12.30 too, but dont have any problem with it? do you use a mod which changed the item ids for most stuff?

**Comment by yukihyou** [comment]
I grabbed the Zip version of the game again (0.12.30) and was unable to replicate the issue.

Seems to be something related to specifically an older Steam version that has been autopatched by Steam. Once I downgraded to stable then back up, it started working fine.

Sorry for the bother.
